config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  mount ActionCable.server, at: '/cable'
  mount Attachinary::Engine => "/attachinary"

  devise_for :users
  root to: 'pages#home'
  resources :searches, only: [:index, :show, :new, :create, :destroy], shallow: true
  resources :results, only: [:show]
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/result.rb
class Result < ApplicationRecord
  geocoded_by :address
  # after_validation :geocode, if: :address_changed?
  belongs_to :search
  # has_attachment :photo

  # after_create :publish_on_cable

  def picture
    if self.img?
       "background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('#{self.img}'); background-size: cover !important; background-position: center;

"
    else
      "background-image: url('#{ActionController::Base.helpers.image_path 'missing_result_pic.svg'}'); background-position: center; background-size: 84%; background-repeat: no-repeat;"
    end
  end

private

  # def publish_on_cable
  #   ActionCable.server.broadcast(
  #     "search_#{self.search.id}",
  #     html: ApplicationController.new.render_to_string(partial: 'searches/result_card', locals: { result: self }, layout: false)
  #   )
  # end
end

app/models/search.rb
class Search < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  belongs_to :type
  belongs_to :user
  has_many :results, dependent: :destroy

  validates :address, :type_id, presence: { message: "Saisissez une adresse valide" }
  validates :budget, numericality: { message: "Veuillez saisir un budget" }
  after_create :scrap_results

  private

  def scrap_results
    Scrapper.set(wait: 3.seconds).perform_later(self.id)
  end
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :searches
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :searches
  has_attachment :photo
  validates :first_name, :last_name, presence: true

  def avatar
    if self.photo?
      ActionController::Base.helpers.cl_image_path self.photo.path
    else
      'avatar_default.svg'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  # include Pundit

  before_action :configure_permitted_parameters, if: :devise_controller?
  # before_action :set_locale

  # after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:phone])
  end

  # def set_locale
  #   I18n.locale = params[:locale] || I18n.default_locale
  # end

  # def default_url_options
  #   # { locale: I18n.locale == I18n.default_locale ? nil : I18n.locale }
  # end


  def default_url_options
    { host: ENV['http://www.happynvestor.fr/']}
  end

   private

  # def skip_pundit?
  #   devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  # end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @search = Search.new
    @types = Type.all.order(name: :asc)
    render layout: "home_layout"
  end

end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :set_result, only: [:show]

  def show
    render layout: false
  end

private

  def set_result
    @result = Result.find(params[:id])
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :find_search, :only => [:show, :destroy]


  def index
    @searches = Search.where(user: current_user)
  end

  def show
    @results = Result.where.not(latitude: nil, longitude: nil).where(search: @search)
    @hash = Gmaps4rails.build_markers(@search) do |search, marker|
      marker.lat search.latitude
      marker.lng search.longitude
      # marker.infowindow render_to_string(partial: "/flats/map_box", locals: { flat: flat })
    end
  end

  def new
  end

  def create
    @search = Search.new(search_params)
    @search.user = current_user
    @types = Type.all.order(name: :asc)
    if @search.save
      redirect_to search_path(@search)
    else
      render 'pages/home', layout: "home_layout"
    end
  end

  def destroy
    @search.destroy
    redirect_to searches_path
  end

  private

  def find_search
    @search = Search.find(params[:id])
  end

  def search_params
    params.require(:search).permit(:address, :type_id, :budget, :surface_min, :room_min, :radius)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def render_navbar
    render 'shared/navbar' unless home
  end

  def display_static_map(search, size)
    zoom = 12
    size = size
    URI.encode("https://maps.googleapis.com/maps/api/staticmap?center=#{search.latitude},#{search.longitude}&zoom=#{zoom}&size=#{size}&markers=color:red|#{search.latitude},#{search.longitude}&key=#{ENV['GOOGLE_API_KEY']}")
  end

  private

  def home
    controller_name == 'pages' && action_name == 'home'
  end
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # ajoutez la ligne ci-dessous pour que le helper fonctionne indifféremment
    # avec une image dans vos assets ou une url absolue
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />


    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>


    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= favicon_link_tag 'favicon-house.png' %>
    <link rel="stylesheet" href="css/animations.css">
  </head>
  <body>

    <%= render_navbar %>
    <%= render 'shared/flashes' %>
    <div class="page-wrap">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API']}" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
    <%#= yield(:meta_title) %>
    <%#= yield(:meta_description) %>
    <%#= yield(:meta_image) %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/layouts/home_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= favicon_link_tag 'favicon-house.png' %>
  </head>
  <body>
    <%= render 'shared/flashes' %>
    <div class="page-wrap">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API']}" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/pages/demo.html.erb
<div class="wrapper">
</div>

app/views/pages/home.html.erb
<div class="home-wrap">
  <div class="banner" style="background-image: linear-gradient(0deg, rgba(0,10,10,0.2) 0%, rgba(0,36,61,0.3) 50%), url(<%= image_url 'no_work.jpg' %>);">
    <div class="log-btns">
      <% if user_signed_in? %>
       <div class="navbar-wagon-item">
          <div class="dropdown">
            <%= image_tag current_user.avatar, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
                <%= link_to searches_path do %>
                  <i class="fa fa-search"></i> <%= t(".profile", default: "Mes recherches") %>
                <% end %>
              </li>
              <li>
                <%= link_to edit_user_registration_path do %>
                  <i class="fa fa-user"></i> <%= t(".profile", default: "Mon profil") %>
                <% end %>
              </li>
              <li>
                <%= link_to root_path do %>
                  <i class="fa fa-home"></i>  <%= t(".profile", default: "Page d'accueil") %>
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Déconnection") %>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      <% else %>
        <%= link_to t(".sign_in", default: "Inscription"), new_user_registration_path, class: "btn btn-success btn-xs" %> &nbsp
        <%= link_to t(".sign_in", default: "Connexion"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <% end %>
    </div>
    <div class="banner-content">
      <div class="banner-title">
        <h1>Happynvestor</h1>
        <br>
        <h2>Investissez au meilleur prix et simplement !</h2>
        <br>
          <%=  render "searches/form", search: @search, types: @types %>
      </div>
      <div class="bottom-arrow text-center">
        <%= image_tag "arrow.svg", class: "floating arrow-img" %>
      </div>
    </div>
  </div>
  <div class="concept-wrap">
    <div class="container">
      <div class="row">
        <div class="col-sm-4">
          <div class="home-card text-center">
            <div class="home-card-title">Rentabilité</div>
            <div class="home-card-img" style= "background-image: url(<%= image_path "profitability.jpg" %>);"></div>
            <div class="home-card-content">
              <p>Nous vous permettons de trouver facilement le bien idéal avec un comparateur de rentabilité</p>
            </div>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="home-card text-center">
            <div class="home-card-title">Simplicité</div>
            <div class="home-card-img" style= "background-image: url(<%= image_path "simplicite.jpg" %>);"></div>
            <div class="home-card-content">
              <p>Nous recensons pour vous toutes les offres immobilières en un seul clic</p>
            </div>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="home-card text-center">
            <div class="home-card-title">Gain de temps</div>
            <div class="home-card-img" style= "background-image: url(<%= image_path "time.jpg" %>);"></div>
            <div class="home-card-content">
              <p>Soyez allerté en temps réel de toutes nouvelles offres par sms</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<%# content_for :meta_title, "Facilitez vos achats avec #{DEFAULT_META["meta_product_name"]}" %>
<%# content_for :meta_description,"Gagnez du temps et de l'argent en quelques clics." %>
<%# content_for :meta_image, cloudinary_url("https://www.whitehouse.gov/sites/whitehouse.gov/files/og-image.png") %>

app/views/results/show.html.erb
<div class="modal-body">
  <div class="header-background" style="<%= @result.picture %>">
    <div class="price"><p><%= @result.price %>€</p></div>
  </div>
  <div class="description"><%= @result.description %></div>
</div>
<div class="modal-footer">
  <%= link_to "Contacter l'annonceur", @result.url, class: "btn btn-primary btn-block", target: "_blank" %>
  <button type="button" class="btn btn-default btn-block" data-dismiss="modal">Fermer</button>
</div>

app/views/searches/_form.html.erb
<%= simple_form_for(search) do |f| %>
  <div class="search-home-form">
    <div class="search-home-form-left">
      <div class="shfl-top">
        <%= f.input :address, placeholder: "Saisissez une Adresse", label: false, class: "address" %>
      </div>
      <div class="shfl-bottom">
        <div class="shfl-bottom-left">
          <%= f.input :budget, placeholder: "Budget max", label: false, class: "budget" %>
        </div>
        <div class="shfl-bottom-right">
          <%= f.input :type_id, collection: types, default: types.first, label: false, class: "type" %>
        </div>
      </div>
    </div>
    <div class="search-home-form-right">

     <%= button_tag( :class => "search-home-form-btn") do %>
                <i class="fa fa-search fa-lg"></i>
        <% end %>
    </div>
  </div>
<% end %>

app/views/searches/_result_card.html.erb
<div class="card" style="<%= result.picture %>">
  <div class="card-description">
    <p><%= result.price %>€</p>
  </div>
  <div class="result-badge result-badge-red"><%= Random.rand(4..12) %>%</div>
  <%= link_to "", local_assigns[:path] ? path : result_path(result), class: "card-link", data: { toggle: "modal", target: "#result-modal" } %>
</div>

app/views/searches/_result_modal.html.erb
<div class="modal fade" id="result-modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/searches/_results_card.html.erb
<% search.results.each do |result| %>
  <% if result %>
    <%= render "searches/result_card", result: result %>
  <% end %>
<% end %>

app/views/searches/_searches_card.html.erb
<div class="search-card">
  <div class="search-card-city">
    <%= search.address.capitalize %>
  </div>
  <div class="search-card-map" style="background-image: url(<%=  display_static_map(search, '300x400')%>)"></div>
  <div class="search-card-content">
    <div class="search-card-content-desc">
      <p class="search-card-content-desc-price"><%= search.budget.to_s.reverse.to_s.gsub(/...(?=.)/,'\& ').reverse %> €</p>
      <p><%= search.type.name %></p>
    </div>
    <div class="search-card-content-icons">
      <div class="badge-container">
        <i class="fa fa-home"></i>
        <div class="badge badge-blue product-count"><%= search.results.size %></div>
      </div>
      <div class="badge-container">
        <i class="fa fa-bar-chart"></i>
        <div class="badge badge-red product-count"><%= Random.rand(4..12) %>%</div>
      </div>
    </div>
  </div>
  <%= link_to "", search, class: "search-card-link" %>
  <%= link_to search_path(search), method: :delete, class: "search-card-delete" do %>
      <i class="fa fa-trash"></i>
  <% end %>

</div>

app/views/searches/create.js.erb
$("#new-search").html("<%=  j render 'searches/form', search: @search, types: @types %>")

app/views/searches/destroy.js.erb
$('[data-search-id=<%= @search.id %>]').slideUp();

app/views/searches/index.html.erb
<div class="searches-wrapper">
  <div class="text-center margin-top-50">
    <span class="title-underline">Vos recherches</span>
  </div>

  <div class="search-card-container">
    <%  @searches.each do |search| %>
      <%= render "searches_card", search: search %>
    <% end %>
  </div>
</div>

<% content_for(:after_js) do %>
  <script>
    $(document).ready(function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
    });
  </script>
<% end %>

app/views/searches/show.html.erb
<% @title = @search.address + " " + @search.budget.to_s + "€" %>
<div class="show-wrapper">
  <div class="search-infos">
    <p>Adresse : <%= @search.address.capitalize %></p>
    <% unless @search.radius.nil? %>
      <p>Rayon : <%= @search.radius %></p>
    <% end %>
    <p>Type de bien : <%= @search.type.name %></p>
    <p>Budget : <%= @search.budget %>€</p>
    <% unless @search.surface_min.nil? %>
      <p>Surface min. : <%= @search.surface_min %>m²</p>
    <% end %>
    <% unless @search.room_min.nil? %>
      <p>Nb. de pièce min. : <%= @search.room_min %></p>
    <% end %>
  </div>
  <div class="show-container">
    <% if @search.results.any? %>
      <div class="results-container">
        <%= render 'results_card', search: @search %>
      </div>
    <% else %>
      <div class="waiting-container text-center">
        <div class="waiting">
          <div class="loading">
            <% (0...7).each do |i| %>
            <div class="loading__square"></div>
            <% end %>
          </div>
        </div>
        <h3>Un instant...</h3>
        <p>Nous recherchons toutes les annonces sur tous les sites immobiliers...</p>
      </div>
    <% end %>
      <div class="map-container" style="background-image: url(<%=  display_static_map(@search, '400x600')%>)"></div>
    <%= render 'result_modal' %>
  </div>
</div>


<%# content_for :meta_title, "Vos recherches" %>
<%# content_for :meta_description, "Gagnez du temps et de l'argent avec HAPPYNVESTOR" %>
<%# content_for :meta_image, cloudinary_url("http://www.hempsteadhouse.co.uk/assets/images/hh-fb-holder.jpg") %>

<% content_for :after_js do %>
  <script>
    $(document).on('ready', function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function(){
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        handler.getMap().setZoom(12);
      });
    });
  </script>

  <script>
    $('body').on('hidden.bs.modal', '.modal', function () {
      $(this).removeData('bs.modal');
    });
  </script>

  <script>
    App.cable.subscriptions.create(
      {
        channel: "SearchChannel",
        search_id: <%= @search.id %>
      },
      {
        connected: function(data) {
          console.log("[CONNECTED]");
        },
        received: function(data) {
          console.log(data);
          $newResult = $(data.html)
          $newResult.hide();
          if ($('.waiting-container').is(':visible')) {
            $('.show-container').prepend('<div class="results-container"></div>');
            $('.waiting-container').hide();
          };
          $('.results-container').prepend($newResult);
          $newResult.slideDown();
        }
      }
    );
  </script>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">
  <div class="container">
    <div class="row">
      <div class="col-xs-4">
        <ul class="list-inline">
          <li><a href="https://www.youtube.com/?hl=fr&gl=FR"><i class="fa fa-youtube"></i></a></li>
          <li><a href="https://www.instagram.com/?hl=fr"><i class="fa fa-instagram"></i></a></li>
          <li><a href="https://www.facebook.com/VroumR/?ref=bookmarks"><i class="fa fa-facebook"></i></a></li>
          <li><a href="https://twitter.com/?lang=fr"><i class="fa fa-twitter"></i></a></li>
        </ul>
      </div>
      <div class="col-xs-8 text-right">
        <p>Made with <i class="fa fa-heart" style="color:red"></i> @LeWagon by Stéphane, Christian, Abdu et Magalie</p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-wagon-fixed">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.svg" %>
    <span class="navbar-wagon-title">Happynvestor</span>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag current_user.avatar, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to searches_path do %>
                <i class="fa fa-search"></i> <%= t(".profile", default: "Mes recherches") %>
              <% end %>
            </li>
            <li>
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Mon profil") %>
              <% end %>
            </li>
            <li>
              <%= link_to root_path do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Page d'accueil") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Déconnection") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>


  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>